version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
  pre_build:
    commands:
      - npm install -g yarn
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - yarn
      - echo 'pre_build Finished.'
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - echo 'Finished.'