version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - npm install -g yarn
      - yarn
      - echo Install complete
    finally:
      - echo Final Install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo Final Pre_build
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - yarn run build
  post_build:
    commands:
      - yarn start
      - echo 'Finished.'