phases:
  install:
    runtime-versions:
       nodejs: 14
    commands:
      - npm install -g yarn
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - yarn
  pre_build:
    commands:
      - echo 'pre_build Finished.'
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - echo 'Finished.'
cache:
  paths:
    - 'node_modules/**/*'