version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Yarn
          commands:
            - echo entered the install phase...
            - curl -o- -L https://yarnpkg.com/install.sh | bash
            - echo install complete
          finally:
            - echo finally install
