version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run:
          name: Check Yarn Version
          command: yarn -v
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Run Tests
          command: yarn test
      - store_artifacts:
          path: ~/repo/test_artifacts
      - store_test_results:
          path: test-results

workflows:
  run-tests-workflow:
    jobs:
      - build
