version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: "curl -o- -L https://yarnpkg.com/install.sh | bash"
